import Head from 'next/head';

import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Contact from '../components/Contact';
import Skills from '../components/Skills';

export default function Home() {
   return (
      <>
         <Head>
            <title>Kevin | Front-End Developer</title>
            <meta content="Generated by create next app" name="description" />
            <meta
               content="width=device-width, initial-scale=1"
               name="viewport"
            />
            <link href="/favicon.ico" rel="icon" />
         </Head>
         <Navbar />
         <Main />
         <Skills />
         <About />
         <Contact />
         <p className="text-sm  p-3 opacity-50 text-center">
            &copy; {new Date().getFullYear()} Kevin Soruco. All rights reserved.
         </p>
      </>
   );
}
